package au.kilemon.messagequeue.message

import org.junit.jupiter.api.Assertions
import java.time.Instant
import java.util.UUID
import java.util.stream.IntStream
import kotlin.test.Test
import kotlin.time.ExperimentalTime
import kotlin.time.toKotlinInstant
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

/**
 * Test functions for [UuidUtils].
 *
 * @author github.com/Kilemonn
 */
class UuidUtilsTest
{
    /**
     * Ensure that the extracted time is the same as what is used to generate the UUID.
     */
    @OptIn(ExperimentalUuidApi::class, ExperimentalTime::class)
    @Test
    fun testGetUuidEpochTimestamp()
    {
        val timeMs = System.currentTimeMillis()
        val instant = Instant.ofEpochMilli(timeMs).toKotlinInstant()
        val uuid = Uuid.generateV7NonMonotonicAt(instant)

        Assertions.assertEquals(timeMs, UuidUtils.getUuidEpochTimestamp(uuid.toString()))

        // Checking after being cast to double they are the same value, since this is what the redis zScore is based off
        // Ensure conversion to double and back to long is correct
        Assertions.assertEquals(timeMs, timeMs.toDouble().toLong())
        Assertions.assertEquals(timeMs.toDouble(), UuidUtils.getUuidEpochTimestamp(uuid.toString()).toDouble())
    }

    /**
     * Ensure that a non-v7 UUID does not fail to parse and that the returned timestamp is just random.
     * This should not happen since all UUIDs are generated by us and it is always generated as a v7 UUID.
     */
    @Test
    fun testGetUuidEpochTimestamp_nonV7UUID()
    {
        val uuid = UUID.randomUUID().toString()
        val parsedTime = UuidUtils.getUuidEpochTimestamp(uuid)

        Assertions.assertNotEquals(-1L, parsedTime)
    }

    /**
     * Ensure an invalid UUID fails to parse and returns -1.
     */
    @Test
    fun testGetUuidEpochTimestamp_invalidUUID()
    {
        val parsedTime = UuidUtils.getUuidEpochTimestamp("not a UUID")
        Assertions.assertEquals(-1L, parsedTime)
    }

    @OptIn(ExperimentalUuidApi::class, ExperimentalTime::class)
    @Test
    fun testUuidGeneration()
    {
        val timestamps = ArrayList<Long>()
        val uuids = ArrayList<String>()

        IntStream.range(0, 100).forEach { _ ->
            val timeMs = System.currentTimeMillis()
            val instant = Instant.ofEpochMilli(timeMs).toKotlinInstant()
            Assertions.assertEquals(timeMs, instant.toEpochMilliseconds())
            uuids.add(Uuid.generateV7NonMonotonicAt(instant).toString())
            timestamps.add(timeMs)
            Thread.sleep(1)
        }

        var previousUuid: String? = null
        var previousScore: Long? = null
        Assertions.assertEquals(timestamps.size, uuids.size)
        for (i in uuids.indices)
        {
            val uuid = uuids[i]
            val timeMs = timestamps[i]
            val parsedTime = UuidUtils.getUuidEpochTimestamp(uuid)
            Assertions.assertEquals(timeMs, parsedTime)

            if (previousUuid != null && previousScore != null)
            {
                // Using org.assertj.core.api.Assertions for better assertion error messages
                org.assertj.core.api.Assertions.assertThat(previousUuid)
                    .isLessThan(uuid)
                org.assertj.core.api.Assertions.assertThat(previousScore)
                    .isLessThan(parsedTime)
            }

            previousUuid = uuid
            previousScore = parsedTime
        }

    }
}
